# Generated by Django 5.2.8 on 2025-12-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(blank=True, help_text='Sube videos (MP4, WebM, MOV), imágenes (JPG, PNG, GIF) o documentos (PDF, DOC, ZIP)', null=True, upload_to='lessons/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL de video (YouTube, Vimeo, etc.) o deja vacío si subes un archivo de video'),
        ),
    ]
