# Generated by Django 5.2.8 on 2025-12-17 22:22

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_lesson_attachment_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='attachment',
            field=models.FileField(blank=True, help_text='Sube videos (MP4, WebM, MOV), imágenes (JPG, PNG, GIF) o documentos (PDF, DOC, ZIP)', null=True, storage=storages.backends.s3.S3Storage(), upload_to='lessons/%Y/%m/%d/'),
        ),
    ]
